# Generated by Django 6.0.6 on 2026-07-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_creditos', models.PositiveIntegerField()),
                ('nivel', models.CharField(max_length=50)),
                ('horas_clase_semana', models.PositiveIntegerField()),
                ('jornada', models.CharField(choices=[('matutina', 'Matutina'), ('vespertina', 'Vespertina'), ('nocturna', 'Nocturna')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='docentes.docente')),
            ],
        ),
    ]
